[terminal]
shell = { program = "/run/current-system/sw/bin/zsh" }

[general]
import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[window]
option_as_alt = "Both"
decorations = "None"

[bell]
duration = 0

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style  = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style  = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style  = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style  = "Bold Italic"

[font.offset]
x = 0
y = 3

[font.glyph_offset]
x = 0
y = 0

# [colors.primary]
# background = "#282c34"
# foreground = "#abb2bf"

